global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAURBAL4NXKJINEXGS
        secret_key: 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
        port: 9100
